"use client";

import { useState, type ReactNode } from "react";
import { cn } from "@/lib/cn";

export type ApprovalCardProps = {
  workflowName: string;
  ageLabel?: string;
  subject: string;
  bodyLines: string[];
  generatedBy: string;
  modelLine?: string;
  onApprove: () => void;
  onEdit?: () => void;
  onReject?: () => void;
  /** Lines describing what happens on approve. */
  diff: string[];
  /** Optional warning/flag line above the actions. */
  flag?: string;
  /** Override the primary action label (default "Approve"). */
  approveLabel?: string;
  rightSlot?: ReactNode;
};

export function ApprovalCard({
  workflowName,
  ageLabel = "14 sec ago",
  subject,
  bodyLines,
  generatedBy,
  modelLine = "Bedrock claude-sonnet (Sydney) · approval-required",
  onApprove,
  onEdit,
  onReject,
  diff,
  flag,
  approveLabel = "Approve",
  rightSlot,
}: ApprovalCardProps) {
  const [diffOpen, setDiffOpen] = useState(true);

  return (
    <article
      className={cn(
        "border border-[var(--color-rule)] bg-[var(--color-paper)]",
        "p-7 md:p-8",
        "wedge-pulse",
      )}
    >
      {/* Header bar */}
      <div className="flex flex-wrap items-baseline justify-between gap-2 border-b border-[var(--color-rule)] pb-3">
        <p className="font-mono text-[0.6875rem] uppercase tracking-[0.22em] text-[var(--color-muted)]">
          Approval queue &middot; pending &middot; {workflowName} &middot; {ageLabel}
        </p>
        <span
          className={cn(
            "inline-flex items-center gap-2 px-2.5 py-1",
            "border",
            "font-mono text-[0.625rem] uppercase tracking-[0.22em]",
          )}
          style={{
            color: "var(--color-signal)",
            borderColor: "var(--color-signal)",
          }}
        >
          <span
            aria-hidden
            className="inline-block h-1.5 w-1.5 rounded-full"
            style={{ background: "var(--color-signal)" }}
          />
          Awaiting approval
        </span>
      </div>

      {/* Subject */}
      <h3 className="mt-5 font-sans text-[1.25rem] tracking-[-0.01em] leading-[1.25] text-[var(--color-ink)]">
        {subject}
      </h3>

      {/* AI-drafted body */}
      <div className="mt-5 border-l border-[var(--color-rule)] pl-5">
        {bodyLines.map((line, i) => (
          <p
            key={i}
            className={cn(
              "font-serif text-[1rem] leading-[1.55] text-[var(--color-ink-2)]",
              i > 0 && "mt-3",
            )}
          >
            {line}
          </p>
        ))}
      </div>

      {/* Right slot for extra panels (e.g. quote line items) */}
      {rightSlot}

      {/* Metadata strip */}
      <p className="mt-6 font-mono text-[0.6875rem] tracking-[0.04em] text-[var(--color-muted)]">
        Generated by {generatedBy} &middot; {modelLine}
      </p>

      {/* Optional flag */}
      {flag ? (
        <p
          className="mt-5 border border-[var(--color-rule)] px-4 py-3 font-mono text-[0.75rem] tracking-[0.02em]"
          style={{ color: "var(--color-signal)", borderColor: "var(--color-signal)" }}
        >
          ⚠ {flag}
        </p>
      ) : null}

      {/* Actions */}
      <div className="mt-6 flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={onApprove}
          className={cn(
            "border border-[var(--color-ink)] bg-[var(--color-ink)] text-[var(--color-paper)]",
            "px-5 py-2.5 font-sans text-[0.875rem] leading-none",
            "hover:bg-[var(--color-ink-2)] transition-colors duration-200",
          )}
        >
          {approveLabel}
        </button>
        <button
          type="button"
          onClick={onEdit}
          className={cn(
            "border border-[var(--color-ink)]",
            "px-5 py-2.5 font-sans text-[0.875rem] leading-none text-[var(--color-ink)]",
            "hover:bg-[var(--color-paper-2)] transition-colors duration-200",
          )}
        >
          Edit
        </button>
        <button
          type="button"
          onClick={onReject}
          className={cn(
            "border border-[var(--color-rule)]",
            "px-5 py-2.5 font-sans text-[0.875rem] leading-none text-[var(--color-ink)]",
            "hover:bg-[var(--color-paper-2)] transition-colors duration-200",
          )}
        >
          Reject
        </button>
        <span className="font-mono text-[0.6875rem] tracking-[0.04em] text-[var(--color-muted)]">
          (asks why &mdash; for the audit log)
        </span>
      </div>

      {/* Diff panel */}
      <div className="mt-6 border border-[var(--color-rule)]">
        <button
          type="button"
          onClick={() => setDiffOpen((v) => !v)}
          aria-expanded={diffOpen}
          className={cn(
            "flex w-full items-center justify-between px-4 py-2.5",
            "font-mono text-[0.6875rem] uppercase tracking-[0.18em] text-[var(--color-ink)]",
            "hover:bg-[var(--color-paper-2)] transition-colors duration-200",
          )}
        >
          <span>On approve &mdash; what happens</span>
          <span aria-hidden className="text-[var(--color-muted)]">
            {diffOpen ? "−" : "+"}
          </span>
        </button>
        <div
          className={cn(
            "grid transition-[grid-template-rows] duration-300 ease-out",
            diffOpen ? "grid-rows-[1fr]" : "grid-rows-[0fr]",
          )}
        >
          <div className="overflow-hidden">
            <ul className="border-t border-[var(--color-rule)] px-4 py-3">
              {diff.map((d, i) => (
                <li
                  key={i}
                  className="font-mono text-[0.75rem] leading-[1.6] tracking-[0.02em] text-[var(--color-ink-2)]"
                >
                  &rarr; {d}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </article>
  );
}

export type ApprovalConfirmationProps = {
  timeLabel: string;
  auditId: string;
  followUps: string[];
};

export function ApprovalConfirmation({
  timeLabel,
  auditId,
  followUps,
}: ApprovalConfirmationProps) {
  return (
    <article
      className={cn(
        "border border-[var(--color-ink)] bg-[var(--color-paper)]",
        "p-7 md:p-8",
      )}
    >
      <div className="flex items-center gap-3">
        <span
          aria-hidden
          className={cn(
            "inline-flex h-8 w-8 items-center justify-center rounded-full",
            "bg-[var(--color-ink)] text-[var(--color-paper)]",
            "font-sans text-[0.875rem] leading-none",
          )}
        >
          ✓
        </span>
        <p className="font-mono text-[0.6875rem] uppercase tracking-[0.22em] text-[var(--color-ink)]">
          Approved &middot; sent at {timeLabel} &middot; audit log entry #{auditId}
        </p>
      </div>

      <ul className="mt-6 flex flex-col gap-2 border-t border-[var(--color-rule)] pt-5">
        {followUps.map((line, i) => (
          <li
            key={i}
            className="font-mono text-[0.8125rem] leading-[1.55] tracking-[0.01em] text-[var(--color-ink-2)]"
          >
            &rarr; {line}
          </li>
        ))}
      </ul>

      <p className="mt-6 font-serif text-[0.9375rem] leading-[1.55] text-[var(--color-muted)]">
        The action happened. The decision was yours. The trail is in the log.
      </p>
    </article>
  );
}
