// AUTO-GENERATED by scripts/gen-article-loaders.mjs — do not edit by hand.
// Run `pnpm articles:gen` after adding or removing an article .mdx file.

export const ARTICLE_SLUGS: readonly string[] = [
  "ai-search-vs-google-perth",
  "google-business-profile-ai-recommend",
  "we-asked-chatgpt-best-tradies-perth",
  "website-invisible-to-ai-fixes",
  "your-next-customer-wont-scroll-google"
];
